server:
    http_listen_port: 9080
    grpc_listen_port: 0

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki:3100/loki/api/v1/push

scrape_configs:
    - job_name: system_logs
      static_configs:
          - targets: ["localhost"]
            labels:
                job: system_logs
                __path__: /var/log/**/*.log # All system logs

    - job_name: spring_logs
      static_configs:
          - targets: ["localhost"]
            labels:
                job: spring_logs
                __path__: /infra/logs/**/*.log # All Spring Boot logs
