auth_enabled: false

server:
    http_listen_port: 3100

common:
    path_prefix: /loki
    storage:
        filesystem:
            chunks_directory: /loki/chunks
            rules_directory: /loki/rules
    replication_factor: 1

schema_config:
    configs:
        - from: 2024-06-16
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
              prefix: index_
              period: 24h

storage_config:
    boltdb:
        directory: /loki/index
    filesystem:
        directory: /loki/chunks

compactor:
    working_directory: /loki/boltdb-shipper-compactor
    compaction_interval: 5m

limits_config:
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    split_queries_by_interval: 24h
    allow_structured_metadata: false

table_manager:
    retention_deletes_enabled: true
    retention_period: 168h

ruler:
    storage:
        type: local
        local:
            directory: /loki/rules

query_range:
    align_queries_with_step: true
    max_retries: 5
    cache_results: true

frontend:
    log_queries_longer_than: 5s
    compress_responses: true
    address: 0.0.0.0:9095

frontend_worker:
    frontend_address: 127.0.0.1:9095

distributor:
    ring:
        kvstore:
            store: inmemory

ingester:
    lifecycler:
        ring:
            kvstore:
                store: inmemory
        final_sleep: 0s

memberlist:
    join_members: []
