global:
    scrape_interval: 15s

scrape_configs:
    - job_name: "prometheus"
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: "node_exporter"
      static_configs:
          - targets: ["node_exporter:9100"]

    - job_name: "spring_app"
      metrics_path: "/actuator/prometheus"
      static_configs:
          - targets:
                - "blue:8080" # Spring Boot Application (Blue Container)
                - "green:8080" # Spring Boot Application (Green Container)
      basic_auth:
          username: "admin" # Prometheus Username
          password: "admin" # Prometheus Password

    - job_name: "loki"
      static_configs:
          - targets: ["loki:3100"]
